### ISSUE TITLE
Implement server-to-client file transfer

### ISSUE THREAD

**Issue by dmaddalena** [rsanchez-wsu/jfiles#289]
File transfer is one of the two core functionalities of the JFiles project (alongside file browsing). This is a broad overview of the file transfer issue and will evolve over time. Implementing this functionality will require, but is not limited to, the following tasks:

- [x] Research FTP and alternatives, then determine an appropriate option for the project. #306 
- [ ] Implement file transfer support server-side (the "send" command). #307 
- [ ] Implement file transfer support client-side (for receiving files). #308

**Comment by SolidStateHero** [comment]
We may need to split this up into more manageable issues, but I think we can avoid that by documenting progress within this issue's comments.

**Comment by rsanchez-wsu** [comment]
@willeko999x you make a good suggestion.

**Comment by orangecraz** [comment]
I found a few articles that we could use to help us get started with this issue. Included is a method for client-server, server-to-client, and two addons to help. Here are some links:
[html5 Doctor: Drag and Drop to automatically send to server](http://html5doctor.com/drag-and-drop-to-server/)
[Pushing Files to the Browser Using Delivery.js, Socket.IO and Node.js](http://liamkaufman.com/blog/2012/02/11/12-pushing-files-to-the-browser-using-deliveryjs-socketio-and-nodejs/)
[NPM: delivery.js](https://www.npmjs.com/package/delivery)
[NPM: scp2](https://www.npmjs.com/package/scp2)
Let me know if these aren't helpful, or what you might need specifically. I'm good with research, so just ask.

**Comment by SolidStateHero** [comment]
@dmaddalena If you are still planning to work on this, please add it to the next milestone and add a description of what you plan to do in the milestone description.
